### ISSUE TITLE
counterpartyd 9.49.3 won't start because version page is down?

### ISSUE THREAD

**Issue by curtislacy** [CounterpartyXCP/counterpartyd#696] opened 2015-02-05 20:53 UTC
Counterpartyd checks https://counterpartyxcp.github.io/counterpartyd/protocol_changes.json to see what version is needed to run.  This file seems to be gone, now?

**Comment by adamkrellenstein** [comment] 2015-02-05 20:54
@ouziel, can you put that file back?

**Comment by deweller** [comment] 2015-02-05 21:26
I'm having the same problem here as well.  Counterpartyd has stopped responding to API requests due to this issue.

**Comment by adamkrellenstein** [comment] 2015-02-05 21:28
@robbydermody is on it. Should be fixed very soon.

**Comment by deweller** [comment] 2015-02-05 21:29
Thanks.

**Comment by robby-dermody** [comment] 2015-02-05 21:58
fixed. please ping if not working for you

**Comment by deweller** [comment] 2015-02-05 21:58
All good now. Thanks.

**Closed by robby-dermody** 2015-02-05 21:58 UTC

**Comment by curtislacy** [comment] 2015-02-05 22:01
Seems to be good for me too, now.

**Comment by mtbitcoin** [comment] 2015-02-06 14:42
Running into the similiar issue of missing "protocol_changes.json "  with the standalone windows counterparty cli tools (https://github.com/CounterpartyXCP/counterparty-cli/releases/tag/v1.0.0). 

I have to first run the "c:\python34\scripts\counterparty-server.exe start" once first before the standalone CLI tools work

**Comment by ouziel-slama** [comment] 2015-02-06 15:04
hum.. weird I just check and the standalone windows binaries contain the file in the correct place (unless you are using counterparyd `develop`).. can you please post the complete error message ?

**Comment by mtbitcoin** [comment] 2015-02-06 15:10
I was using the one at https://github.com/CounterpartyXCP/counterparty-cli/releases/tag/v1.0.0

But the issue is not present anymore after running c:\python34\scripts\counterparty-server.exe start once.

**Comment by ouziel-slama** [comment] 2015-02-06 15:40
OK, I will try to reproduce.

**Comment by mtbitcoin** [comment] 2015-02-06 16:02
@ouziel-slama : Sorry, the issue only applied to the standalone C:\counterparty-cli-win32-1.0.0>counterparty-client.exe  (NOT server)
